title: Digitales Brett
subtitle: Fachschaft Mathematik und Informatik, Universität Marburg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Die Fachschaft erhält in unregelmäßigen Abständen Informationen zu Jobs, Praktika sowie Stipendien, aber auch Veranstaltungen und Ähnlichem von Firmen, Universitäten oder Stiftungen.
  
url: "https://brett.fs-matheinfo.de"

#sidebar
default-image: 

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 24
paginate_path: /page:num/

#social
facebook: http://facebook.com/
quora: http://quora.com/
twitter: http://twitter.com/
github: http://github.com/
email: fachschaft@mathematik.uni-marburg,de

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
