name: Custom Build and Deploy to Github Pages

on:
  push:
    branches:
      - main
  
  # Register on dispatch from Digitales-Brett
  repository_dispatch:
    types: [triggerJekyllBuild]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout this repository
      - uses: actions/checkout@v2
      
      # Checkout content repository
      - uses: actions/checkout@v2
        with:
          repository: Fachschaft-FB12/Digitales-Brett
          path: content
          
      # Move the data from content to the desired directory    
      - name: Move attachments and posts data
        run: |
          echo "Show attachments from external repo"
          ls content/attachments
          mv content/attachments .
          echo "Show posts from external repo"
          ls content/*
          mv content/* _posts

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Copy the Jekyll build to branch gh-pages
      - uses: jeffreytse/jekyll-deploy-action@v0.3.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
